# Generated by Django 5.0.6 on 2024-05-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizzap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
